BillOfMaterialx.project_class = 'ExtConstructionProjectx::Project'
BillOfMaterialx.supplier_class = 'Supplierx::Supplier'
BillOfMaterialx.manufacturer_class = 'Manufacturerx::Manufacturer'
BillOfMaterialx.customer_class = 'Kustomerx::Customer'
BillOfMaterialx.task_class = 'EventTaskx::EventTask'
